program: run_pipeline_full_options_sweep.py # Your main script file
method: bayes # Search strategy: bayes, random, grid
metric:
  name: average/mAUROC_px # Metric to optimize (logged to wandb summary)
  goal: maximize # maximize or minimize
parameters:
  loss_func:
    distribution: categorical
    value:
    - "CosLoss" # Test different loss functions
  optimizer:
    distribution: categorical
    value:
      - "AdamW"
  model:
     distribution: categorical
     values:
     - "ViTAD_Fusion_v2"
     - "ViTAD_Fusion"
  lr:
    values: [0.0001, 0.0002, 0.0008, 0.0016]

  weight_decay:
    values: [0.0001, 0.0002, 0.0004, 0.00001]

  batch_size:
    values: [ 16, 32 ]

  epochs:
    value: 100
  val_epochs:
    value: 25

